### ISSUE TITLE
babel 6 support

### ISSUE THREAD

**Issue by jasonmit** [thejameskyle/babel-plugin-handlebars-inline-precompile#1]
Are there plans to support Babel 6?  I'd love to help but can't seem to find any good resources on the new babel plugin architecture.

**Comment by thejameskyle** [comment]
> I'd love to help but can't seem to find any good resources on the new babel plugin architecture.

https://github.com/thejameskyle/babel-plugin-handbook

**Comment by thejameskyle** [comment]
Fixed in https://github.com/thejameskyle/babel-plugin-handlebars-inline-precompile/commit/30f2fe4bda7d3b22b7f18be33567fa4363429c5b
