### ISSUE TITLE
Ability to require external .hbs files

### ISSUE THREAD

**Issue by DylanPiercey** [thejameskyle/babel-plugin-handlebars-inline-precompile#11]
This might be out of the scope of this module but I am looking for something that will let me directly require precompiled handlebars templates.

```js
const ExternalTemplate = require('./my-template.hbs');
```

```js
import _Handlebars from 'handlebars/runtime';
const ExternalTemplate = _Handlebars.template({ /* A bunch of crazy template stuff */ });
```

Not sure how easy this is to do with babel, not much experience writing plugins.

**Comment by thejameskyle** [comment]
Might want to just use a webpack loader or browserify transform for that

**Comment by DylanPiercey** [comment]
I was hoping to use this in an Isomorphic situation.

**Comment by thejameskyle** [comment]
Theres plenty of other build tools that would be better suited for that

**Comment by DylanPiercey** [comment]
@thejameskyle do you have any recommendations?

**Comment by thejameskyle** [comment]
You could use something like [`gulp-handlebars`](https://www.npmjs.com/package/gulp-handlebars). I'm surprised Handlebars doesn't ship with a CLI tool or a node require extension.

**Comment by DylanPiercey** [comment]
Currently using gulp-handlebars, it's a bit gross though. I also thought that there would be a require extension but couldn't find one. Thanks anyway @thejameskyle.
