### ISSUE TITLE
Plugin can't throw errors with Babel 6

### ISSUE THREAD

**Issue by novemberborn** [thejameskyle/babel-plugin-handlebars-inline-precompile#9]
I've been implementing a plugin as my own, using this one as a guide. Turns out `this.errorWithNode()` is no longer available in Babel 6, having been replaced with `throw path.buildCodeFrameError()`.

I can do a PR to fix this but I'd have to add some tests as well. Does [this approach](https://github.com/novemberborn/babel-plugin-import-glob/blob/3d957838d93f13867981ed158e22da870359ddd9/test/import-glob.js#L4:L26) seem sensible to you?

* Attempt to do the transform in-memory
* Test the error type and message

Incidentally I'm using [AVA](https://github.com/sindresorhus/ava). It's got built-in ES2015 support so is less faff to run than Mocha. Would you accept a PR that swaps out the test runner?

**Comment by thejameskyle** [comment]
Could you do those PRs separately?

**Comment by novemberborn** [comment]
> Could you do those PRs separately?

I've done #10 containing the fixes. I'll leave Mocha be I think.
